# PART A: VECTOR & MATRIX FUNDAMENTALS

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Rows = Students, Columns = Subjects (Math, Science, English, Computer)
data = np.array([
    [85, 78, 92, 88],
    [75, 82, 79, 85],
    [90, 88, 94, 92],
    [60, 65, 70, 68],
    [80, 78, 85, 82]
])

students = ["S1", "S2", "S3", "S4", "S5"]
subjects = ["Math", "Science", "English", "Computer"]

df = pd.DataFrame(data, index=students, columns=subjects)
df

,Math,Science,English,Computer
S1,85,78,92,88
S2,75,82,79,85
S3,90,88,94,92
S4,60,65,70,68
S5,80,78,85,82


In [5]:
#1. Represent each student as vector

v1 = data[0]  # Student 1
v2 = data[1]  # Student 2

print("Student 1 Vector:", v1)
print("Student 2 Vector:", v2)

Student 1 Vector: [85 78 92 88]
Student 2 Vector: [75 82 79 85]


In [26]:
#2. Calculate
#a) Norm-1 and Norm-2

# L1 Norm
l1 = np.linalg.norm(v1, ord=1)

# L2 Norm
l2 = np.linalg.norm(v1)

print("L1 Norm:", l1)
print("L2 Norm:", l2)

L1 Norm: 343.0
L2 Norm: 171.80512215879943


In [27]:
#b) Dot Product & Angle

dot = np.dot(v1, v2)

# angle
angle = np.arccos(dot / (np.linalg.norm(v1) * np.linalg.norm(v2)))
angle_deg = np.degrees(angle)

print("Dot Product:", dot)
print("Angle (degrees):", angle_deg)

Dot Product: 27519
Angle (degrees): 4.497772294973425


In [28]:
# c)Cross Product

cross = np.cross(v1[:3], v2[:3])
print("Cross Product:", cross)

Cross Product: [-1382   185  1120]


In [29]:
# 3) Projection of one vector onto another

projection = (np.dot(v1, v2) / np.dot(v2, v2)) * v2
print("Projection of v1 on v2:", projection)

Projection of v1 on v2: [79.95061011 87.41266705 84.21464265 90.61069146]


# PART B: MATRIX OPERATIONS

In [30]:
#4) Matrix Representation

A = data
print("Matrix A:\n", A)

Matrix A:
 [[85 78 92 88]
 [75 82 79 85]
 [90 88 94 92]
 [60 65 70 68]
 [80 78 85 82]]


In [31]:
#a) Matrix Addition & Multiplication

# Addition
add = A + A

# Multiplication
mul = np.dot(A, A.T)

print("Addition:\n", add)
print("Multiplication:\n", mul)

Addition:
 [[170 156 184 176]
 [150 164 158 170]
 [180 176 188 184]
 [120 130 140 136]
 [160 156 170 164]]
Multiplication:
 [[29517 27519 31258 22594 27920]
 [27519 25815 29212 21140 26081]
 [31258 29212 33144 23956 29598]
 [22594 21140 23956 17349 21396]
 [27920 26081 29598 21396 26433]]


In [32]:
#b) Transpose, Inverse, Determinant

# Transpose
transpose = A.T

# Square matrix for inverse
B = A[:4, :4]

det = np.linalg.det(B)
inv = np.linalg.inv(B)

print("Transpose:\n", transpose)
print("Determinant:", det)
print("Inverse:\n", inv)

Transpose:
 [[85 75 90 60 80]
 [78 82 88 65 78]
 [92 79 94 70 85]
 [88 85 92 68 82]]
Determinant: 30549.999999999964
Inverse:
 [[-6.54664484e-05 -9.42716858e-03  1.13387889e-01 -1.41538462e-01]
 [-1.66939444e-01 -3.92798691e-02  1.39116203e-01  7.69230769e-02]
 [-1.47299509e-02 -1.21112930e-01  1.22749591e-02  1.53846154e-01]
 [ 1.74795417e-01  1.70540098e-01 -2.45662848e-01 -9.23076923e-02]]


# PART C: LINEAR TRANSFORMATION

In [33]:
# 5) Line, Plane, Hyperplane

'''
Line (1D) → vector span
Plane (2D) → combination of 2 vectors
Hyperplane → higher dimensions'''


# Linear combination
a, b = 2, 3
result = a*v1 + b*v2
print(result)

[395 402 421 431]


In [34]:
# 6) Dimensionality Increase

# Original data (4D)
print("Original Shape:", A.shape)

# Add new feature: Total marks (new dimension)
total = np.sum(A, axis=1).reshape(-1, 1)

A_new = np.hstack((A, total))

print("New Data:\n", A_new)
print("New Shape:", A_new.shape)

Original Shape: (5, 4)
New Data:
 [[ 85  78  92  88 343]
 [ 75  82  79  85 321]
 [ 90  88  94  92 364]
 [ 60  65  70  68 263]
 [ 80  78  85  82 325]]
New Shape: (5, 5)


# PART D: EIGENVALUES & DECOMPOSITION

In [35]:
#7) Covariance Matrix + Eigenvalues

# Covariance matrix
cov = np.cov(A, rowvar=False)

# Eigenvalues & vectors
eigenvalues, eigenvectors = np.linalg.eig(cov)

print("Covariance Matrix:\n", cov)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Covariance Matrix:
 [[132.5   85.5  111.25 101.25]
 [ 85.5   71.2   65.5   73.25]
 [111.25  65.5   96.5   82.25]
 [101.25  73.25  82.25  84.  ]]
Eigenvalues:
 [3.62382781e+02 1.96866408e+01 2.50835245e-01 1.87974311e+00]
Eigenvectors:
 [[ 0.60123695  0.2459497  -0.68916977 -0.32104191]
 [ 0.40768818 -0.7324303   0.30488176 -0.45208773]
 [ 0.49838437  0.56927282  0.65306191 -0.03242862]
 [ 0.47319922 -0.28103924 -0.07484841  0.83156308]]


In [36]:
#8) LU Decomposition

from scipy.linalg import lu

P, L, U = lu(B)

print("L:\n", L)
print("U:\n", U)

L:
 [[ 1.          0.          0.          0.        ]
 [ 0.83333333  1.          0.          0.        ]
 [ 0.66666667  0.73076923  1.          0.        ]
 [ 0.94444444 -0.58974359  0.52808989  1.        ]]
U:
 [[90.         88.         94.         92.        ]
 [ 0.          8.66666667  0.66666667  8.33333333]
 [ 0.          0.          6.84615385  0.57692308]
 [ 0.          0.          0.          5.72097378]]


In [37]:
#9) Singular Value Decomposition (SVD)

U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("Singular Values:\n", S)
print("Vt:\n", Vt)

U:
 [[-0.4723394   0.59825055  0.19461921  0.61594285 -0.04158755]
 [-0.44154089 -0.74901061 -0.17604478  0.45111371  0.09761867]
 [-0.50077911  0.09576273 -0.45771073 -0.37459257 -0.62468478]
 [-0.36215008 -0.20819526  0.82802909 -0.34661693 -0.14045135]
 [-0.44721889  0.16900775 -0.18973748 -0.39578773  0.76077816]]
Singular Values:
 [363.51066219   9.55531589   4.47410189   2.58395595]
Vt:
 [[-0.48373011 -0.48290252 -0.51930885 -0.51296068]
 [ 0.4524237  -0.69890876  0.48778083 -0.26250562]
 [-0.74918815 -0.11433585  0.62738218  0.17898608]
 [ 0.00592325 -0.51503302 -0.31429251  0.79744976]]


# PART E: DIMENSIONALITY REDUCTION


In [38]:
#10) PCA (Reduce to 2D)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
reduced = pca.fit_transform(A)

print("Reduced Data (2D):\n", reduced)

Reduced Data (2D):
 [[ 10.48019205  -5.01712035]
 [ -1.80001917   6.92952684]
 [ 20.4528242    1.06304544]
 [-30.27911849  -1.4867544 ]
 [  1.14612141  -1.48869752]]


In [39]:
#11) LDA Classification

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Labels: Above avg (1), Below avg (0)
labels = [1, 1, 1, 0, 1]

lda = LinearDiscriminantAnalysis(n_components=1)
lda_result = lda.fit_transform(A, labels)

print("LDA Result:\n", lda_result)

LDA Result:
 [[-1.02379595]
 [-0.67678852]
 [-2.11504974]
 [ 3.50705444]
 [ 0.30857977]]
